### ISSUE TITLE
Write a bootstrap startup command in the Dockerfile

### ISSUE THREAD

**Issue by sixeyed** [docker/communitytools-image2docker-win#26]
For any features which run as Windows Services, add a `Start-Service` command in a bootstrap file, and set the bootstrap as the Dockerfile's `CMD` instruction.

**Comment by StefanScherer** [comment]
Or is a tool like the microsoft/iis ServiceMonitor.exe a thing? https://github.com/Microsoft/iis-docker/issues/1 OK, it still isn't open sourced, but I like the idea of a generic Windows Service <-> CMD helper, probably monitoring multiple services (and logging the event log of the service to stdout/stderr).

**Comment by sixeyed** [comment]
Yes, I was thinking that too. I guess [Wait-Service](https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Wait-Service) will have to do until ServiceMonitor.exe gets OS though, so it won't have the logging piece.
