### ISSUE TITLE
Handle `Path Not Found` due to multiple virtual hard disks

### ISSUE THREAD

**Issue by BrandonRoyal** [docker/communitytools-image2docker-win#41]
Where path does not exist due to missing virtual disk, process should have the option for skip files that aren't accessible rather than failing.

**Comment by BrandonRoyal** [comment]
@sixeyed looks like we should be checking if the physical path exists before we attempt the copy

https://github.com/docker/communitytools-image2docker-win/blob/master/Functions/Private/Artifacts/IIS/Generate_IIS.ps1#L73

**Comment by pdevine** [comment]
I'm going to close this in favour of #38, which is roughly the same thing.
