### ISSUE TITLE
GetManifestFromApplicationHost error

### ISSUE THREAD

**Issue by jontreynes** [docker/communitytools-image2docker-win#54]
Here's the build
VERBOSE: User specified the Force Parameter. Removing existing items from
c:\Image2Docker\backup\auto_image2docker\mywebapp
VERBOSE: User specified path c:\Image2Docker\backup\auto_image2docker\mywebapp has been created
VERBOSE: Reading image file: C:\VMs\WS16-IIS - Copy.vhdx
VERBOSE: Image file appears to be a valid WIM or VHDX file.
VERBOSE: Image file C:\VMs\WS16-IIS - Copy.vhdx contains 1 images
VERBOSE: This image appears to be a valid Virtual Hard Drive (VHDX) file.
VERBOSE: Image type is: VHDX
VERBOSE: User didn't specify a mount path. Using:
C:\Users\joreynes\AppData\Local\Temp\0663f122-a68f-4d57-a24a-18862d9e0861-mount
VERBOSE: Finished mounting image c:\VMs\WS16-IIS - Copy.vhdx at mount point
C:\Users\joreynes\AppData\Local\Temp\0663f122-a68f-4d57-a24a-18862d9e0861-mount
VERBOSE: Finished mounting image to: C:\Users\joreynes\AppData\Local\Temp\0663f122-a68f-4d57-a24a-18862d9e0861-mount
VERBOSE: Starting conversion process
VERBOSE: Started discovering IIS artifact
VERBOSE: Checking IIS ApplicationHost config for Windows Version: 10.0
VERBOSE: Finished dismounting the Windows image from
C:\Users\joreynes\AppData\Local\Temp\0663f122-a68f-4d57-a24a-18862d9e0861-mount
GetManifestFromApplicationHost : Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error:
"There is an unclosed literal string. Line 900, position 87."
At C:\Program Files\WindowsPowerShell\Modules\Image2Docker\1.8.1\Functions\Private\Artifacts\IIS\Discover_IIS.ps1:51
char:27
+ ... estResult = GetManifestFromApplicationHost -OutputPath $OutputPath -M ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [GetManifestFromApplicationHost], RuntimeException
    + FullyQualifiedErrorId : InvalidCastToXmlDocument,GetManifestFromApplicationHost

**Comment by pdevine** [comment]
Is it possible to get a sample of your `\Windows\System32\inetsrv\config\applicationHost.config` file? It looks like the XML isn't being parsed correctly.

**Comment by pdevine** [comment]
ping @jontreynes. Do you have a copy of the XML file?

**Comment by jontreynes** [comment]
Hello, sorry for the very late reply @pdevine. I don't remember if I resolved this issue. My apologies. I just checked to see that file, but it does not exist. Maybe that was why? I am closing this issue now
